server:
  port: 8082

spring:
  profiles:
    active: prod
  cloud:
    stream:
      bindings:
        input0:
          destination: kyee_test_3
          contentType: application/json
          group: CID_kyee_consumer
          consumer:
            concurrency: 5
            headerMode: embeddedHeaders
            partitioned: true
            maxAttempts: 3
      kafka:
        bindings:
          input0:
            consumer:
              #单个消费实例挂掉之后 自动重新分片 (考虑到分区有序，
              #单个线程消费多个partition并不会带来顺序问题, 所有实例正常的情况下，每个线程默认只消费一个固定的partition
              #重要的是每个partition有且只能有一个线程消费它)
              autoRebalanceEnabled: true
              autoCommitOffset: true
              autoCommitOnError: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/message2?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: admin
    tomcat:
      validation-query: "select 1"
